spring.application.name=nl2sql-backend
server.port=8080

# =============================== 
# Database configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/nl2sql_admin_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver
#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =============================== 
# Google Gemini AI Configuration 
# ===============================
gemini.api.key=AIzaSyDV6zbXY0J_emmSBPVDLeE39-Z0WzRmf0Y
spring.ai.openai.api-key=${gemini.api.key}
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-2.5-flash
# spring.ai.openai.chat.options.model=gemini-1.5-flash
# Model này sẽ tự động biến Metadata thành Vector
# Tắt tự động nhúng (vì đã tự viết Custom Client)
spring.ai.openai.embedding.enabled=false

# Tắt tự động kết nối Qdrant của Spring AI (vì đã dùng QdrantConfig tự viết)
spring.autoconfigure.exclude=org.springframework.ai.autoconfigure.vectorstore.qdrant.QdrantVectorStoreAutoConfiguration
# =============================== 
# Qdrant Vector DB (gRPC)
# ===============================
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=schema_metadata