spring.application.name=nl2sql-backend
server.port=8080

# =============================== 
# Database configuration
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/nl2sql_admin_db
spring.datasource.username=admin
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver
#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =============================== 
# Google Gemini AI Configuration 
# ===============================
spring.ai.openai.api-key=AIzaSyDZdcHjdWteUwy11myKHESXGd8RfS49ado
spring.ai.openai.base-url=https://generativelanguage.googleapis.com/v1beta/openai/
spring.ai.openai.chat.options.model=gemini-2.5-flash
# Model này sẽ tự động biến Metadata thành Vector
spring.ai.openai.embedding.options.model=text-embedding-004

# =============================== 
# Qdrant Vector DB (gRPC)
# ===============================
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=schema_metadata